{% set version = '0.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-colourpicker
  version: {{ version|replace("-", "_") }}

source:
  fn: colourpicker_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/colourpicker_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/colourpicker/colourpicker_{{ version }}.tar.gz


  sha256: fede03259a60322c2af70e1b4642a4aa9bb5731768a5690712acadc61da5bd6b
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr (>= 1.7), rmarkdown, rstudioapi (>= 0.5)
requirements:
  build:
    - r-base
    - r-ggplot2
    - r-htmltools
    - r-htmlwidgets >=0.7
    - r-miniui >=0.1.1
    - r-shiny >=0.11.1
    - r-shinyjs

  run:
    - r-base
    - r-ggplot2
    - r-htmltools
    - r-htmlwidgets >=0.7
    - r-miniui >=0.1.1
    - r-shiny >=0.11.1
    - r-shinyjs

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('colourpicker')"  # [not win]
    - "\"%R%\" -e \"library('colourpicker')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/daattali/colourpicker
  license: MIT + file LICENSE
  summary: A colour picker that can be used as an input in Shiny apps or 'Rmarkdown' documents.
    A Plot Colour Helper tool is available as an  'RStudio' addin, which helps you pick
    colours to use in your plots. A more  generic Colour Picker 'RStudio' addin is also
    provided to let you select  colours for use in your R code.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: colourpicker
# Type: Package
# Title: A Colour Picker Tool for Shiny and for Selecting Colours in Plots
# Version: 0.3
# Authors@R: person("Dean", "Attali", email = "daattali@gmail.com", role = c("aut", "cre"))
# Description: A colour picker that can be used as an input in Shiny apps or 'Rmarkdown' documents. A Plot Colour Helper tool is available as an  'RStudio' addin, which helps you pick colours to use in your plots. A more  generic Colour Picker 'RStudio' addin is also provided to let you select  colours for use in your R code.
# URL: https://github.com/daattali/colourpicker
# BugReports: https://github.com/daattali/colourpicker/issues
# Depends: R (>= 3.1.0)
# Imports: ggplot2, htmltools, htmlwidgets (>= 0.7), miniUI (>= 0.1.1), shiny (>= 0.11.1), shinyjs, utils
# Suggests: knitr (>= 1.7), rmarkdown, rstudioapi (>= 0.5)
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-12-05 22:13:18 UTC; Dean
# Author: Dean Attali [aut, cre]
# Maintainer: Dean Attali <daattali@gmail.com>
# Repository: CRAN
# Date/Publication: 2016-12-05 23:30:42

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
