package:
  name: fisher
  version: "0.1.4"

source:
  fn: fisher-0.1.4.tar.gz
  url: https://files.pythonhosted.org/packages/b2/03/da73cc8582c34bafbc4ec4b572f9691c9ae5d0ae743a359b1d16414439f9/fisher-0.1.4.tar.gz
  sha256: bba9e4ece8dda18f7e67fee487947a5ac28ed2bb138600da8b214ac051f87ebf

build:
  skip: True #  [just py27]
  number: 0

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - fisher

about:
  home: http://github.com/brentp/fishers_exact_test
  license: BSD License
  summary: "Fast Fisher's Exact Test"


extra:
  recipe-maintainers:
    - brittainhard
