{% set xorg_name = "libX11" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.6.4" %}
{% set sha256 = "b7c748be3aa16ec2cbd81edc847e9b6ee03f88143ab270fb59f58a044d34e441" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 6
  detect_binary_files_with_prefix: true
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]
  always_include_files:
    # Workaround for dummy X11 headers in OSX `tk` package
    - include/X11/cursorfont.h
    - include/X11/ImUtil.h
    - include/X11/Xcms.h
    - include/X11/XKBlib.h
    - include/X11/XlibConf.h
    - include/X11/Xlib.h
    - include/X11/Xlibint.h
    - include/X11/Xlib-xcb.h
    - include/X11/Xlocale.h
    - include/X11/Xregion.h
    - include/X11/Xresource.h
    - include/X11/Xutil.h

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - m2w64-pkg-config  # [win]
    - m2w64-toolchain  # [win]
    - pkg-config  # [not win]
    - posix  # [win]
    - python  # [win]
    - toolchain
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
    - xorg-inputproto
    - xorg-kbproto
    - libxcb 1.*
    - pthread-stubs
    - xorg-util-macros
    - xcb-proto
    - xorg-xextproto
    - xorg-xproto
    - xorg-xtrans
    - xorg-libxau
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
    - xorg-kbproto
    - libxcb 1.*
    - xorg-xproto

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'The main client library for X Windows version 11.'

extra:
  recipe-maintainers:
    - pkgw
