{% set version = "0.3.0" %}

package:
  name: pamela
  version: {{ version }}

source:
  fn: pamela-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pamela/pamela-{{ version }}.tar.gz
  md5: de6516118d51eb5fc97017f3b6d5c68b

build:
  number: 0
  skip: true  # [win]
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - pamela

about:
  home: https://github.com/minrk/pamela
  license: MIT
  summary: PAM interface using ctypes

extra:
  recipe-maintainers:
    - minrk
