{% set version = '3.18.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bma
  version: {{ version|replace("-", "_") }}

source:
  fn: BMA_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/BMA_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/BMA/BMA_{{ version }}.tar.gz


  sha256: bf18170fa45577a27355967cf440b12c41795ed6804759eebce1d12917e5b124
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, forward
requirements:
  build:
    - r-base
    - r-inline
    - r-leaps
    - r-robustbase
    - r-rrcov
    - r-survival
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-inline
    - r-leaps
    - r-robustbase
    - r-rrcov
    - r-survival
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('BMA')"  # [not win]
    - "\"%R%\" -e \"library('BMA')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.research.att.com/~volinsky/bma.html
  license: GPL (>= 2)
  summary: Package for Bayesian model averaging and variable selection for linear models, generalized
    linear models and survival models (cox regression).
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: BMA
# Version: 3.18.7
# Date: 2017-05-11
# Title: Bayesian Model Averaging
# Author: Adrian Raftery <raftery@uw.edu>, Jennifer Hoeting, Chris Volinsky, Ian Painter, Ka Yee Yeung
# Maintainer: Hana Sevcikova <hanas@uw.edu>
# Description: Package for Bayesian model averaging and variable selection for linear models, generalized linear models and survival models (cox regression).
# Depends: survival, leaps, robustbase, inline, rrcov
# Imports: methods
# Suggests: MASS, forward
# License: GPL (>= 2)
# URL: http://www.research.att.com/~volinsky/bma.html
# NeedsCompilation: yes
# Packaged: 2017-05-11 23:29:47 UTC; hana
# Repository: CRAN
# Date/Publication: 2017-05-12 06:16:04 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
