{% set version = '1.1-1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-partykit
  version: {{ version|replace("-", "_") }}

source:
  fn: partykit_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/partykit_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/partykit/partykit_{{ version }}.tar.gz


  sha256: d9f4762690cd85ee4e3dc44f5a14069d10a1900afdfbcdc284d2a94b4a8e8332
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: XML, pmml, rJava, rpart, mvtnorm, sandwich, strucchange, vcd, AER, mlbench, TH.data (>= 1.0-3), coin (>= 1.1-0), RWeka (>= 0.4-19), datasets, parallel, psychotools, psychotree
requirements:
  build:
    - r-base
    - r-formula >=1.2_1
    - r-survival
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-formula >=1.2_1
    - r-survival
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('partykit')"  # [not win]
    - "\"%R%\" -e \"library('partykit')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://partykit.R-Forge.R-project.org/partykit
  license: GPL-2 | GPL-3
  summary: A toolkit with infrastructure for representing, summarizing, and visualizing tree-structured
    regression and classification models. This unified infrastructure can be used for
    reading/coercing tree models from different sources ('rpart', 'RWeka', 'PMML') yielding
    objects that share functionality for print()/plot()/predict() methods. Furthermore,
    new and improved reimplementations of conditional inference trees (ctree()) and
    model-based recursive partitioning (mob()) from the 'party' package are provided
    based on the new infrastructure.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: partykit
# Title: A Toolkit for Recursive Partytioning
# Date: 2016-09-20
# Version: 1.1-1
# Authors@R: c(person(given = "Torsten", family = "Hothorn", role = c("aut", "cre"), email = "Torsten.Hothorn@R-project.org"), person(given = "Achim", family = "Zeileis", role = "aut", email = "Achim.Zeileis@R-project.org"))
# Description: A toolkit with infrastructure for representing, summarizing, and visualizing tree-structured regression and classification models. This unified infrastructure can be used for reading/coercing tree models from different sources ('rpart', 'RWeka', 'PMML') yielding objects that share functionality for print()/plot()/predict() methods. Furthermore, new and improved reimplementations of conditional inference trees (ctree()) and model-based recursive partitioning (mob()) from the 'party' package are provided based on the new infrastructure.
# Depends: R (>= 3.1.0), graphics, grid
# Imports: grDevices, stats, utils, survival, Formula (>= 1.2-1)
# Suggests: XML, pmml, rJava, rpart, mvtnorm, sandwich, strucchange, vcd, AER, mlbench, TH.data (>= 1.0-3), coin (>= 1.1-0), RWeka (>= 0.4-19), datasets, parallel, psychotools, psychotree
# LazyData: yes
# License: GPL-2 | GPL-3
# URL: http://partykit.R-Forge.R-project.org/partykit
# NeedsCompilation: yes
# Packaged: 2016-09-20 13:00:01 UTC; hothorn
# Author: Torsten Hothorn [aut, cre], Achim Zeileis [aut]
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Repository: CRAN
# Date/Publication: 2016-09-20 15:39:04

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
