{% set version = '1.0-7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-truncnorm
  version: {{ version|replace("-", "_") }}

source:
  fn: truncnorm_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/truncnorm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/truncnorm/truncnorm_{{ version }}.tar.gz


  sha256: c7d775d09e2dcbcc543c03a207b4407b8548b5fdfeb4c017f12818507e014ce1
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base 3.4.1
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base 3.4.1
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('truncnorm')"  # [not win]
    - "\"%R%\" -e \"library('truncnorm')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=truncnorm
  license: GPL-2
  summary: r/d/p/q functions for the truncated normal distribution
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: truncnorm
# Version: 1.0-7
# Title: Truncated normal distribution
# Description: r/d/p/q functions for the truncated normal distribution
# Author:  Heike Trautmann <trautmann@statistik.uni-dortmund.de> and Detlef Steuer <detlef.steuer@hsu-hamburg.de> and Olaf Mersmann <olafm@statistik.uni-dortmund.de> and BjArn Bornkamp <bornkamp@statistik.tu-dortmund.de>
# Maintainer: Olaf Mersmann <olafm@statistik.uni-dortmund.de>
# Depends: R (>= 2.15.0)
# License: GPL-2
# Encoding: UTF-8
# Date:
# Packaged: 2014-01-21 08:56:20 UTC; olafm
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2014-01-21 10:17:26

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
