{% set version = '1.4-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rrcov
  version: {{ version|replace("-", "_") }}

source:
  fn: rrcov_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rrcov_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rrcov/rrcov_{{ version }}.tar.gz


  sha256: d89631e0dfb39777af9fe303cc0537bbc82c6f3d2a1ed360de950c13dfc34f4d
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: grid, mclust, MASS, ellipse
requirements:
  build:
    - r-base
    - r-cluster
    - r-lattice
    - r-mvtnorm
    - r-pcapp
    - r-robustbase >=0.92_1
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-cluster
    - r-lattice
    - r-mvtnorm
    - r-pcapp
    - r-robustbase >=0.92_1
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rrcov')"  # [not win]
    - "\"%R%\" -e \"library('rrcov')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=rrcov
  license: GPL (>= 2)
  summary: Robust Location and Scatter Estimation and Robust Multivariate Analysis with High
    Breakdown Point.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: rrcov
# Version: 1.4-3
# Date: 2016-09-03
# Title: Scalable Robust Estimators with High Breakdown Point
# Author: Valentin Todorov <valentin.todorov@chello.at>
# Description: Robust Location and Scatter Estimation and Robust Multivariate Analysis with High Breakdown Point.
# Maintainer: Valentin Todorov <valentin.todorov@chello.at>
# Depends: R (>= 2.10), robustbase (>= 0.92-1), methods
# Imports: stats, stats4, mvtnorm, lattice, cluster, pcaPP
# Suggests: grid, mclust, MASS, ellipse
# LazyLoad: yes
# License: GPL (>= 2)
# Repository: CRAN
# Packaged: 2016-09-05 22:49:02 UTC; Share
# NeedsCompilation: yes
# Date/Publication: 2016-09-06 08:03:44

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
