package:
  name: oauth
  version: "1.0.1"

source:
  fn: oauth-1.0.1.tar.gz
  url: https://pypi.python.org/packages/e2/10/d7d6ae26ef7686109a10b3e88d345c4ec6686d07850f4ef7baefb7eb61e1/oauth-1.0.1.tar.gz
  md5: 30ed3cc8c11d7841a89feab437aabf81

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - oauth

about:
  home: http://code.google.com/p/oauth
  license: MIT License
  summary: 'Library for OAuth version 1.0a.'
  license_family: MIT

extra:
  recipe-maintainers:
    - brittainhard
