{% set version = '0.0.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dtplyr
  version: {{ version|replace("-", "_") }}

source:
  fn: dtplyr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/dtplyr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/dtplyr/dtplyr_{{ version }}.tar.gz


  sha256: c59419ad4d236f7b9dcbc900316cd869d686d9bdad2420e1b5dd7d51a6ede5e0
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: Lahman, nycflights13, testthat, covr
requirements:
  build:
    - r-base
    - r-data.table
    - r-dplyr >=0.5.0
    - r-lazyeval

  run:
    - r-base
    - r-data.table
    - r-dplyr >=0.5.0
    - r-lazyeval

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('dtplyr')"  # [not win]
    - "\"%R%\" -e \"library('dtplyr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hadley/dtplyr
  license: GPL (>= 2)
  summary: This implements the data table back-end for 'dplyr' so that you can seamlessly use
    data table and 'dplyr' together.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: dtplyr
# Title: Data Table Back-End for 'dplyr'
# Version: 0.0.2
# Authors@R: c( person("Lionel", "Henry", , "lionel@rstudio.com", role = "cre"), person("Hadley", "Wickham", , "hadley@rstudio.com", role = "aut"), person("RStudio", role = "cph") )
# Description: This implements the data table back-end for 'dplyr' so that you can seamlessly use data table and 'dplyr' together.
# License: GPL (>= 2)
# Imports: dplyr (>= 0.5.0), data.table, lazyeval
# Suggests: Lahman, nycflights13, testthat, covr
# LazyData: true
# RoxygenNote: 6.0.1
# URL: https://github.com/hadley/dtplyr
# BugReports: https://github.com/hadley/dtplyr/issues
# NeedsCompilation: no
# Packaged: 2017-04-21 21:54:36 UTC; lionel
# Author: Lionel Henry [cre], Hadley Wickham [aut], RStudio [cph]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-04-21 23:49:45 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
