package:
    name: geneimpacts
    version: 0.3.1
source:
    fn: geneimpacts-0.3.1.tar.gz
    sha256: 03b2c5ca07dd490472329981cf9700d1473780451f052be7459c644ce7f31a50
    url: https://files.pythonhosted.org/packages/7e/01/cbb6820939cc08bab0a9b4487836523608e94928ff626204c42cb70db42b/geneimpacts-0.3.1.tar.gz
build:
    skip: True #  [not py27]
    number: '0'
requirements:
    build:
        - python
        - setuptools
    run:
        - python
test:
    imports:
        - geneimpacts
about:
    home: https://github.com/brentp/geneimpacts
    license: MIT
    summary: prioritize effects of variant annotations from VEP, SnpEff, et al.
