package:
  name: python-docx
  version: 0.8.6

source:
  fn: python-docx-0.8.6.tar.gz
  url: https://pypi.io/packages/source/p/python-docx/python-docx-0.8.6.tar.gz
  sha256: 55ece6fd4a4fa3389909fa0e51400fce428e1fb6f6ef3599cbba31673441f184

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - lxml >=2.3.2

test:
  imports:
    - docx
    - docx.dml
    - docx.enum
    - docx.image
    - docx.opc
    - docx.opc.parts
    - docx.oxml
    - docx.oxml.text
    - docx.parts
    - docx.styles
    - docx.text

about:
  home: https://github.com/python-openxml/python-docx
  license: MIT
  license_file: LICENSE
  summary: 'Create and update Microsoft Word .docx files.'

extra:
  recipe-maintainers:
    - brittainhard
