{% set name = "knnimpute" %}
{% set version = "0.1.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4a05857be4b883a6d690c4c9e07e2920b324c30c97b7ed6241e0bdfb0bcb7af0" %}

package:
  version: '{{ version }}'
  name: '{{ name|lower }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'
  fn: '{{ name }}-{{ version }}.tar.gz'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  run:
    - python
    - six
    - numpy >=1.10
  build:
    - python
    - setuptools
    - six
    - numpy >=1.10

test:
  imports:
    - knnimpute

about:
  dev_url: ''
  description: "|Build Status| |Coverage Status|\n\nknnimpute\n=========\n\nMultiple implementations of kNN imputation in pure Python + NumPy\n\n.. |Build Status| image:: https://travis-ci.org/hammerlab/knnimpute.svg?branch=master\n\
    \   :target: https://travis-ci.org/hammerlab/knnimpute\n.. |Coverage Status| image:: https://coveralls.io/repos/github/hammerlab/knnimpute/badge.svg?branch=master\n   :target: https://coveralls.io/github/hammerlab/knnimpute?branch=master\n"
  license: Apache Software License
  license_family: APACHE
  summary: k-Nearest Neighbor imputation
  home: https://github.com/hammerlab/knnimpute
  license_file: ''
  doc_url: ''

extra:
  recipe-maintainers: ''
