{% set version = '1.1-7.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-algdesign
  version: {{ version|replace("-", "_") }}

source:
  fn: AlgDesign_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/AlgDesign_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/AlgDesign/AlgDesign_{{ version }}.tar.gz


  sha256: df0d56111401474b7f06eaf9ce7145a1cb73b3c5ec4817bad06f56db48af872e
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('AlgDesign')"  # [not win]
    - "\"%R%\" -e \"library('AlgDesign')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/jvbraun/AlgDesign
  license: GPL (>= 2)
  summary: Algorithmic experimental designs. Calculates exact and approximate theory experimental
    designs for D,A, and I criteria. Very large designs may be created. Experimental
    designs may be blocked or blocked designs created from a candidate list, using several
    criteria.  The blocking can be done when whole and within plot factors interact.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: AlgDesign
# Version: 1.1-7.3
# Date: 2011/10/14
# Title: Algorithmic Experimental Design
# Author: Bob Wheeler <bwheelerg@gmail.com>
# Maintainer: Jerome Braun <jvbraun.statistics@gmail.com>
# Description: Algorithmic experimental designs. Calculates exact and approximate theory experimental designs for D,A, and I criteria. Very large designs may be created. Experimental designs may be blocked or blocked designs created from a candidate list, using several criteria.  The blocking can be done when whole and within plot factors interact.
# License: GPL (>= 2)
# URL: https://github.com/jvbraun/AlgDesign
# Packaged: 2014-10-15 00:35:38 UTC; Speculator
# Repository: CRAN
# Date/Publication: 2014-10-15 02:39:28
# NeedsCompilation: yes

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
