package:
    name: cairocffi
    version: 0.8.0
source:
    fn: cairocffi-0.8.0.tar.gz
    patches:
        - dlopen-patch.linux.txt
    url: https://pypi.io/packages/source/c/cairocffi/cairocffi-0.8.0.tar.gz
    sha256: 65f21e6786e2b255ab1d3fda53a365a3565bb1808cabbbe59d99a797c61d3545
        
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record record.txt
requirements:
    build:
        - python
        - cffi >=1.1.0
        - cairo 1.14.*
    run:
        - python
        - cffi >=1.1.0
        - cairo 1.14.*
test:
    imports:
        - cairocffi
about:
    home: https://github.com/SimonSapin/cairocffi
    license: BSD 3-Clause
    license_family: BSD
    summary: cffi-based cairo bindings for Python
extra:
    recipe-maintainers:
        - brittainhard
