package:
    name: schema-salad
    version: 2.6.20170806163416
source:
    fn: schema-salad-2.6.20170806163416.tar.gz
    sha256: af414fd5f89cf452e3581cda9fd403278db72256a6ed6bc13f62a19bb38fae46
    url: https://files.pythonhosted.org/packages/fa/cb/707b7624e786e3a90d9fd3bb312612f1cc0ee2e7dcad79e26d4493ea9bf9/schema-salad-2.6.20170806163416.tar.gz
build:
    entry_points:
        - schema-salad-tool=schema_salad.main:main
    number: '0'
    skip: True  # [py3k]
requirements:
    build:
        - python
        - setuptools
        - requests
        - rdflib >=4.2.0
        - rdflib-jsonld >=0.3.0
        - mistune
        - typing >=3.5.2,<3.6
        - ruamel.yaml >=0.12.4
        - cachecontrol
        - lockfile
        - avro-python2
    run:
        - python
        - requests
        - rdflib >=4.2.0
        - rdflib-jsonld >=0.3.0
        - mistune
        - typing >=3.5.2,<3.6
        - ruamel.yaml >=0.12.4
        - cachecontrol
        - lockfile
        - avro-python2
test:
    commands:
        - schema-salad-tool --help
    imports:
        - schema_salad
about:
    home: https://github.com/common-workflow-language/schema_salad
    license: Apache 2.0
    summary: Schema Annotations for Linked Avro Data (SALAD)
