{% set name = "opentargets" %}
{% set version = "2.0.2" %}
{% set hash_type = "sha256" %}
{% set hash_value = "7b294721d0e2c62eb1e27197143f7a64b53e1e6d055d0ba835c6a1ec732f3d06" %}

package:
  version: '{{ version }}'
  name: '{{ name|lower }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'
  fn: '{{ name }}-{{ version }}.tar.gz'

build:
  number: 0
  script: 'python setup.py install '

requirements:
  run:
    - python
    - requests >=2.11.1,<3.0
    - cachecontrol ==0.11.6
    - hyper ==0.7.0
    - h2 ==2.4.2
    - future ==0.16.0
    - pyyaml
  build:
    - python
    - requests >=2.11.1,<3.0
    - cachecontrol ==0.11.6
    - hyper ==0.7.0
    - h2 ==2.4.2
    - future ==0.16.0
    - pyyaml

test:
  imports:
    - opentargets

about:
  dev_url: ''
  description: ''
  license: Apache License, Version 2.0
  license_family: APACHE
  summary: Client for Open Targets REST API at targetvalidation.org
  home: https://github.com/opentargets/opentargets-py
  license_file: ''
  doc_url: ''

extra:
  recipe-maintainers:
      - brittainhard
