package:
  name: opentargets
  version: 2.0.2

source:
  fn: opentargets-2.0.2.tar.gz
  url: https://pypi.python.org/packages/bf/df/b6f4833df829561569bd7d47ef2deb90b3ebb30d93e618b248d3c3443088/opentargets-2.0.2.tar.gz
  md5: 1961742f5f01d4effe103cedef8626b3

build:
  number: 0

requirements:
  build:
    - python
    - requests >=2.11.1,<3.0
    - cachecontrol ==0.11.6
    - hyper ==0.7.0
    - h2 ==2.4.2
    - future ==0.16.0
    - pyyaml

  run:
    - python
    - requests >=2.11.1,<3.0
    - cachecontrol ==0.11.6
    - hyper ==0.7.0
    - h2 ==2.4.2
    - future ==0.16.0
    - pyyaml

test:
  imports:
    - opentargets

about:
  home: https://github.com/opentargets/opentargets-py
  license: Apache License, Version 2.0
  summary: 'Client for Open Targets REST API at targetvalidation.org'
  license_family: APACHE

extra:
  recipe-maintainers:
    - brittainhard
