package:
  name: pygame
  version: "1.9.3"

source:
  fn: pygame-1.9.3.tar.gz
  url: https://pypi.python.org/packages/61/06/3c25051549c252cc6fde01c8aeae90b96831370884504fe428a623316def/pygame-1.9.3.tar.gz
  md5: ac744ea6952b68d5f2b6d02a6d8e836c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pygame = pygame:main
    #
    # Would create an entry point called pygame that calls pygame.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - sdl2

  run:
    - python

test:
  # Python imports
  imports:
    - pygame
    - pygame.docs
    - pygame.examples
    - pygame.gp2x
    - pygame.tests
    - pygame.tests.run_tests__tests
    - pygame.tests.run_tests__tests.all_ok
    - pygame.tests.run_tests__tests.everything
    - pygame.tests.run_tests__tests.exclude
    - pygame.tests.run_tests__tests.failures1
    - pygame.tests.run_tests__tests.incomplete
    - pygame.tests.run_tests__tests.incomplete_todo
    - pygame.tests.run_tests__tests.infinite_loop
    - pygame.tests.run_tests__tests.print_stderr
    - pygame.tests.run_tests__tests.print_stdout
    - pygame.tests.run_tests__tests.timeout
    - pygame.tests.test_utils
    - pygame.threads

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.pygame.org
  license: LGPL
  summary: 'Python Game Development'
  license_family: LGPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
