{% set version = '2.3.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sparkr
  version: {{ version|replace("-", "_") }}

source:


  git_url: https://github.com/apache/spark
  git_tag: master
  # You can add a hash for the file here, like md5, sha1 or sha256
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, testthat, e1071, survival
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('SparkR')"  # [not win]
    - "\"%R%\" -e \"library('SparkR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.apache.org/ http://spark.apache.org/
  license: Apache License (== 2.0)
  summary: Provides an R Frontend for Apache Spark.
  license_family: APACHE

# The original CRAN metadata for this package was:

# Package: SparkR
# Type: Package
# Version: 2.3.0
# Title: R Frontend for Apache Spark
# Description: Provides an R Frontend for Apache Spark.
# Authors@R: c(person("Shivaram", "Venkataraman", role = c("aut", "cre"), email = "shivaram@cs.berkeley.edu"), person("Xiangrui", "Meng", role = "aut", email = "meng@databricks.com"), person("Felix", "Cheung", role = "aut", email = "felixcheung@apache.org"), person(family = "The Apache Software Foundation", role = c("aut", "cph")))
# License: Apache License (== 2.0)
# URL: http://www.apache.org/ http://spark.apache.org/
# BugReports: http://spark.apache.org/contributing.html
# Depends: R (>= 3.0), methods
# Suggests: knitr, rmarkdown, testthat, e1071, survival
# Collate: 'schema.R' 'generics.R' 'jobj.R' 'column.R' 'group.R' 'RDD.R' 'pairRDD.R' 'DataFrame.R' 'SQLContext.R' 'WindowSpec.R' 'backend.R' 'broadcast.R' 'catalog.R' 'client.R' 'context.R' 'deserialize.R' 'functions.R' 'install.R' 'jvm.R' 'mllib_classification.R' 'mllib_clustering.R' 'mllib_fpm.R' 'mllib_recommendation.R' 'mllib_regression.R' 'mllib_stat.R' 'mllib_tree.R' 'mllib_utils.R' 'serialize.R' 'sparkR.R' 'stats.R' 'streaming.R' 'types.R' 'utils.R' 'window.R'
# RoxygenNote: 5.0.1
# VignetteBuilder: knitr

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
