{% set version = '1.3.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-httpuv
  version: {{ version|replace("-", "_") }}

source:
  fn: httpuv_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/httpuv_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/httpuv/httpuv_{{ version }}.tar.gz


  sha256: 4336b993afccca2a194aca577b1975b89a35ac863423b18a11cdbb3f8470e4e9
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - r-rcpp
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rcpp
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('httpuv')"  # [not win]
    - "\"%R%\" -e \"library('httpuv')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/rstudio/httpuv
  license: GPL-3 | file LICENSE
  summary: Provides low-level socket and protocol support for handling HTTP and WebSocket requests
    directly from within R. It is primarily intended as a building block for other packages,
    rather than making it particularly easy to create complete web applications using
    httpuv alone. httpuv is built on top of the libuv and http-parser C libraries, both
    of which were developed by Joyent, Inc. (See LICENSE file for libuv and http-parser
    license information.)
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: httpuv
# Type: Package
# Title: HTTP and WebSocket Server Library
# Version: 1.3.5
# Author: Joe Cheng, Hector Corrada Bravo [ctb], Jeroen Ooms [ctb], Winston Chang [ctb]
# Copyright: RStudio, Inc.; Joyent, Inc.; Nginx Inc.; Igor Sysoev; Niels Provos; Internet Systems Consortium, Inc.; Alexander Chemeris
# Maintainer: Joe Cheng <joe@rstudio.com>
# Description: Provides low-level socket and protocol support for handling HTTP and WebSocket requests directly from within R. It is primarily intended as a building block for other packages, rather than making it particularly easy to create complete web applications using httpuv alone. httpuv is built on top of the libuv and http-parser C libraries, both of which were developed by Joyent, Inc. (See LICENSE file for libuv and http-parser license information.)
# License: GPL-3 | file LICENSE
# Depends: R (>= 2.15.1), methods
# Imports: Rcpp (>= 0.11.0), utils
# LinkingTo: Rcpp
# URL: https://github.com/rstudio/httpuv
# SystemRequirements: GNU make
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-07-03 21:47:04 UTC; jcheng
# Repository: CRAN
# Date/Publication: 2017-07-04 07:02:15 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
