{% set name = "cwlref-runner" %}
{% set version = "1.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a46662940c1e13453c1cb955167ef2223331449c58b026b7f06c905726aad619" %}

package:
  version: '{{ version }}'
  name: '{{ name|lower }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'
  fn: '{{ name }}-{{ version }}.tar.gz'

build:
  entry_points:
    - cwl-runner=cwltool.main:main
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  run:
    - python
    - cwltool
  build:
    - python
    - setuptools
    - cwltool

test:
  commands:
    - cwl-runner --help

about:
  dev_url: ''
  description: 'This an optional companion package to "cwltool" which provides provides an

    additional entry point under the alias "cwl-runner", which is the

    implementation-agnostic name for the default CWL interpreter installed on a

    host.'
  license: Apache 2.0
  license_family: APACHE
  summary: Common workflow language reference implementation
  home: http://www.commonwl.org
  license_file: ''
  doc_url: ''

extra:
  recipe-maintainers:
    - brittainhard
