{% set version = '1.2-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-formula
  version: {{ version|replace("-", "_") }}

source:
  fn: Formula_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/Formula_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/Formula/Formula_{{ version }}.tar.gz


  sha256: 8def4600fb7457d38db8083733477501b54528974aa216e4adf8871bff4aa429
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('Formula')"  # [not win]
    - "\"%R%\" -e \"library('Formula')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=Formula
  license: GPL-2 | GPL-3
  summary: Infrastructure for extended formulas with multiple parts on the right-hand side and/or
    multiple responses on the left-hand side (see <DOI:10.18637/jss.v034.i01>).
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: Formula
# Version: 1.2-2
# Date: 2017-07-11
# Title: Extended Model Formulas
# Description: Infrastructure for extended formulas with multiple parts on the right-hand side and/or multiple responses on the left-hand side (see <DOI:10.18637/jss.v034.i01>).
# Authors@R: c(person(given = "Achim", family = "Zeileis", role = c("aut", "cre"), email = "Achim.Zeileis@R-project.org"), person(given = "Yves", family = "Croissant", role = "aut", email = "Yves.Croissant@univ-reunion.fr"))
# Depends: R (>= 2.0.0), stats
# License: GPL-2 | GPL-3
# NeedsCompilation: no
# Packaged: 2017-07-10 23:09:07 UTC; zeileis
# Author: Achim Zeileis [aut, cre], Yves Croissant [aut]
# Maintainer: Achim Zeileis <Achim.Zeileis@R-project.org>
# Repository: CRAN
# Date/Publication: 2017-07-10 23:28:09 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
