package:
  name: openpyxl
  version: 1.8.6

source:
  fn: openpyxl-1.8.6.tar.gz
  url: https://files.pythonhosted.org/packages/c2/ae/4ac6659a37bac4c496cc59378b95e5fbbaf3c1d6249827bb7c7516de979a/openpyxl-1.8.6.tar.gz
  sha256: aa11a4acd2765392808bca2041f6f9ba17565c72dccc3f5d876bf78effa06126

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - jdcal
    - et_xmlfile

  run:
    - python
    - jdcal
    - et_xmlfile

test:
  imports:
    - openpyxl
    - openpyxl.cell
    - openpyxl.chart
    - openpyxl.chartsheet
    - openpyxl.comments
    - openpyxl.compat
    - openpyxl.descriptors
    - openpyxl.drawing
    - openpyxl.formatting
    - openpyxl.formula
    - openpyxl.packaging
    - openpyxl.pivot
    - openpyxl.reader
    - openpyxl.styles
    - openpyxl.utils
    - openpyxl.workbook
    - openpyxl.workbook.external_link
    - openpyxl.worksheet
    - openpyxl.writer
    - openpyxl.xml

about:
  home: https://openpyxl.readthedocs.io
  license: MIT License
  summary: 'A Python library to read/write Excel 2010 xlsx/xlsm files'
  license_family: MIT

extra:
  recipe-maintainers:
    - brittainhard
