# This file created by conda-build 2.1.7
# meta.yaml template originally from:
# /home/ilan/anaconda/packages/openpyxl, last modified Tue May 16 10:52:49 2017
# ------------------------------------------------

package:
    name: openpyxl
    version: 2.4.7
source:
    fn: openpyxl-2.4.7.tar.gz
    md5: 3b72f8cc142aea30032cda73ffb57b02
    url: https://pypi.python.org/packages/1e/90/80833aecb57c4218a886fe3ecbf7bde0963bf0cb43d60015dee3ea790c36/openpyxl-2.4.7.tar.gz
build:
    noarch: ''
    noarch_python: false
    string: py36_0
requirements:
    build:
        - setuptools 27.2.0 py36_0
        - zlib 1.2.8 3
        - jdcal 1.3 py36_0
        - sqlite 3.13.0 0
        - python 3.6.1 2
        - xz 5.2.2 1
        - openssl 1.0.2k 2
        - et_xmlfile 1.0.1 py36_0
        - readline 6.2 2
        - tk 8.5.18 0
    run:
        - python
        - jdcal
        - et_xmlfile
test:
    imports:
        - openpyxl
about:
    description: 'Openpyxl is a Python library for reading and writing Excel 2010

        xlsx/xlsm/xltx/xltm files. It was born from lack of existing library to

        read/write natively from Python the Office Open XML format.

        '
    dev_url: https://bitbucket.org/openpyxl/openpyxl/src
    doc_url: http://openpyxl.readthedocs.org
    home: http://openpyxl.readthedocs.org
    license: MIT
    license_file: README.rst
    summary: A Python library to read/write Excel 2010 xlsx/xlsm files
extra:
    final: true
