# This file created by conda-build 2.0.7
# meta.yaml template originally from:
# /opt/recipe, last modified Fri May  5 20:11:19 2017
# ------------------------------------------------

package:
    name: mygene
    version: 3.0.0
source:
    fn: mygene-3.0.0.tar.gz
    sha256: 36e5e42e05ade82141b7a82e5f9249546fabe5e9f47fe18c1535e6cedc603314
    url: https://files.pythonhosted.org/packages/53/94/6c9975eef99f64cecef912de80615223abfb6dab804bc600b4fe1104eee8/mygene-3.0.0.tar.gz
build:
    skip: 'False'
requirements:
    build:
        - python
        - setuptools
        - requests >=2.3.0
    run:
        - python
        - requests >=2.3.0
test:
    imports:
        - mygene
about:
    home: https://github.com/suLab/mygene.py
    license: BSD License
    license_family: BSD
    summary: Python Client for MyGene.Info services.
