{% set version = '1.2.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-infotheo
  version: {{ version|replace("-", "_") }}

source:
  fn: infotheo_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/infotheo_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/infotheo/infotheo_{{ version }}.tar.gz


  sha256: 9b47ebc3db5708c88dc014b4ffec6734053a9c255a9241fcede30fec3e63aaa3
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('infotheo')"  # [not win]
    - "\"%R%\" -e \"library('infotheo')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://homepage.meyerp.com/software
  license: GPL (>= 3)
  summary: This package implements various measures of information theory based on several entropy
    estimators.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: infotheo
# Title: Information-Theoretic Measures
# Version: 1.2.0
# Date: 2014-07
# Publication: 2009-08-14
# Author: Patrick E. Meyer
# Description: This package implements various measures of information theory based on several entropy estimators.
# Maintainer: Patrick E. Meyer <software@meyerp.com>
# License: GPL (>= 3)
# URL: http://homepage.meyerp.com/software
# Repository: CRAN
# Packaged: 2014-07-25 15:20:26 UTC; master
# NeedsCompilation: yes
# Date/Publication: 2014-07-26 08:08:09

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
