{% set version = '1.4-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vcd
  version: {{ version|replace("-", "_") }}

source:
  fn: vcd_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/vcd_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/vcd/vcd_{{ version }}.tar.gz


  sha256: 17ce89927421d9cd01285b6093eeaaecb1e7252388007f66d3b9222e58cc5f15
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: KernSmooth, mvtnorm, kernlab, HSAUR, coin
requirements:
  build:
    - r-base 3.4.1
    - r-mass
    - r-colorspace
    - r-lmtest

  run:
    - r-base 3.4.1
    - r-mass
    - r-colorspace
    - r-lmtest

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('vcd')"  # [not win]
    - "\"%R%\" -e \"library('vcd')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=vcd
  license: GPL-2
  summary: Visualization techniques, data sets, summary and inference procedures aimed particularly
    at categorical data. Special emphasis is given to highly extensible grid graphics.
    The package was package was originally inspired by the book  "Visualizing Categorical
    Data" by Michael Friendly and is  now the main support package for a new book,  "Discrete
    Data Analysis with R" by Michael Friendly and  David Meyer (2015).
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: vcd
# Version: 1.4-3
# Title: Visualizing Categorical Data
# Authors@R: c(person(given = "David", family = "Meyer", role = c("aut", "cre"), email = "David.Meyer@R-project.org"), person(given = "Achim", family = "Zeileis", role = c("aut")), person(given = "Kurt", family = "Hornik", role = c("aut")), person(given = "Florian", family = "Gerber", role = c("ctb")), person(given = "Michael", family = "Friendly", role = "ctb"))
# Description: Visualization techniques, data sets, summary and inference procedures aimed particularly at categorical data. Special emphasis is given to highly extensible grid graphics. The package was package was originally inspired by the book  "Visualizing Categorical Data" by Michael Friendly and is  now the main support package for a new book,  "Discrete Data Analysis with R" by Michael Friendly and  David Meyer (2015).
# LazyLoad: yes
# LazyData: yes
# Depends: R (>= 2.4.0), grid
# Suggests: KernSmooth, mvtnorm, kernlab, HSAUR, coin
# Imports: stats, utils, MASS, grDevices, colorspace, lmtest
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2016-09-17 09:16:30 UTC; meyer
# Author: David Meyer [aut, cre], Achim Zeileis [aut], Kurt Hornik [aut], Florian Gerber [ctb], Michael Friendly [ctb]
# Maintainer: David Meyer <David.Meyer@R-project.org>
# Repository: CRAN
# Date/Publication: 2016-09-17 17:55:20

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
