{% set version = '0.6-0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xgboost
  version: {{ version|replace("-", "_") }}

source:
  fn: xgboost_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/xgboost_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/xgboost/xgboost_{{ version }}.tar.gz


  sha256: 3c7993596eec6503ee5b65c5b6f2562acb8e41562acc3ca61bbb6c19f6273fe1
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, ggplot2 (>= 1.0.1), DiagrammeR (>= 0.9.0), Ckmeans.1d.dp (>= 3.3.1), vcd (>= 1.3), testthat, igraph (>= 1.0.1)
requirements:
  build:
    - r-base
    - r-matrix >=1.1_0
    - r-data.table >=1.9.6
    - r-magrittr >=1.5
    - r-stringi >=0.5.2
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]
    - libxgboost 0.60

  run:
    - r-base
    - r-matrix >=1.1_0
    - r-data.table >=1.9.6
    - r-magrittr >=1.5
    - r-stringi >=0.5.2
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]
    - libxgboost 0.60

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('xgboost')"  # [not win]
    - "\"%R%\" -e \"library('xgboost')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/dmlc/xgboost
  license: Apache License (== 2.0) | file LICENSE
  summary: Extreme Gradient Boosting, which is an efficient implementation of the gradient boosting
    framework from Chen & Guestrin (2016) <doi:10.1145/2939672.2939785>. This package
    is its R interface. The package includes efficient linear  model solver and tree
    learning algorithms. The package can automatically  do parallel computation on a
    single machine which could be more than 10  times faster than existing gradient
    boosting packages. It supports various objective functions, including regression,
    classification and ranking. The package is made to be extensible, so that users
    are also allowed to define their own objectives easily.
  license_family: APACHE

# The original CRAN metadata for this package was:

# Package: xgboost
# Type: Package
# Title: Extreme Gradient Boosting
# Version: 0.6-4
# Date: 2017-01-04
# Author: Tianqi Chen <tianqi.tchen@gmail.com>, Tong He <hetong007@gmail.com>, Michael Benesty <michael@benesty.fr>, Vadim Khotilovich <khotilovich@gmail.com>, Yuan Tang <terrytangyuan@gmail.com>
# Maintainer: Tong He <hetong007@gmail.com>
# Description: Extreme Gradient Boosting, which is an efficient implementation of the gradient boosting framework from Chen & Guestrin (2016) <doi:10.1145/2939672.2939785>. This package is its R interface. The package includes efficient linear  model solver and tree learning algorithms. The package can automatically  do parallel computation on a single machine which could be more than 10  times faster than existing gradient boosting packages. It supports various objective functions, including regression, classification and ranking. The package is made to be extensible, so that users are also allowed to define their own objectives easily.
# License: Apache License (== 2.0) | file LICENSE
# URL: https://github.com/dmlc/xgboost
# BugReports: https://github.com/dmlc/xgboost/issues
# VignetteBuilder: knitr
# Suggests: knitr, rmarkdown, ggplot2 (>= 1.0.1), DiagrammeR (>= 0.9.0), Ckmeans.1d.dp (>= 3.3.1), vcd (>= 1.3), testthat, igraph (>= 1.0.1)
# Depends: R (>= 3.3.0)
# Imports: Matrix (>= 1.1-0), methods, data.table (>= 1.9.6), magrittr (>= 1.5), stringi (>= 0.5.2)
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2017-01-05 06:38:47 UTC; hetong007
# Repository: CRAN
# Date/Publication: 2017-01-05 10:40:06

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
