{% set version = '2.8.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-curl
  version: {{ version|replace("-", "_") }}

source:
  fn: curl_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/curl_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/curl/curl_{{ version }}.tar.gz


  sha256: 554352a56d213a3a32bc262f4662c5a40b1fdcf264da5ecab6116562f9a1ee35
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat (>= 1.0.0), knitr, jsonlite, rmarkdown, magrittr, httpuv, webutils
requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('curl')"  # [not win]
    - "\"%R%\" -e \"library('curl')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/jeroen/curl#readme (devel) https://curl.haxx.se/libcurl/ (upstream)
  license: MIT + file LICENSE
  summary: The curl() and curl_download() functions provide highly configurable drop-in replacements
    for base url() and download.file() with better performance, support for encryption
    (https, ftps), gzip compression, authentication, and other 'libcurl' goodies. The
    core of the package implements a framework for performing fully customized requests
    where data can be processed either in memory, on disk, or streaming via the callback
    or connection interfaces. Some knowledge of 'libcurl' is recommended; for a more-user-friendly
    web client see the 'httr' package which builds on this package with http specific
    tools and logic.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: curl
# Type: Package
# Title: A Modern and Flexible Web Client for R
# Version: 2.8.1
# Authors@R: c( person("Jeroen", "Ooms", , "jeroen@berkeley.edu", role = c("cre", "aut")), person("Hadley", "Wickham", , "hadley@rstudio.com", role = "ctb"), person("RStudio", role = "cph") )
# Description: The curl() and curl_download() functions provide highly configurable drop-in replacements for base url() and download.file() with better performance, support for encryption (https, ftps), gzip compression, authentication, and other 'libcurl' goodies. The core of the package implements a framework for performing fully customized requests where data can be processed either in memory, on disk, or streaming via the callback or connection interfaces. Some knowledge of 'libcurl' is recommended; for a more-user-friendly web client see the 'httr' package which builds on this package with http specific tools and logic.
# License: MIT + file LICENSE
# SystemRequirements: libcurl: libcurl-devel (rpm) or libcurl4-openssl-dev (deb).
# URL: https://github.com/jeroen/curl#readme (devel) https://curl.haxx.se/libcurl/ (upstream)
# BugReports: https://github.com/jeroen/curl/issues
# Suggests: testthat (>= 1.0.0), knitr, jsonlite, rmarkdown, magrittr, httpuv, webutils
# VignetteBuilder: knitr
# Depends: R (>= 3.0.0)
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-07-20 10:47:34 UTC; jeroen
# Author: Jeroen Ooms [cre, aut], Hadley Wickham [ctb], RStudio [cph]
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2017-07-21 23:02:20 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
