{% set name = "scikit-monaco" %}
{% set version = "0.2.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "bb3d4e2a7830b6af68c82fb47ce12afe6dc332bf762f1ee823ef1e6c5ac17ba3" %}

package:
  version: '{{ version }}'
  name: '{{ name|lower }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'
  fn: '{{ name }}-{{ version }}.tar.gz'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - nose
  run:
    - python
    - numpy

test:
  imports:
    - skmonaco

