{% set name = "ipython-genutils" %}
{% set version = "0.2.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "eb2e116e75ecef9d4d228fdc66af54269afa26ab4463042e33785b887c628ba8" %}

package:
  version: '{{ version }}'
  name: '{{ name|lower }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/ipython_genutils/ipython_genutils-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'
  fn: 'ipython_genutils-{{ version }}.tar.gz'

build:
  number: 0
  script: 'python setup.py install '

requirements:
  run:
    - python
  build:
    - python

test:
  imports:
    - ipython_genutils
    - ipython_genutils.testing
    - ipython_genutils.tests

about:
  dev_url: ''
  description: 'Pretend this doesn''t exist. Nobody should use it.



    '
  license: BSD License
  license_family: BSD
  summary: Vestigial utilities from IPython
  home: http://ipython.org
  license_file: ''
  doc_url: ''

extra:
  recipe-maintainers:
    - brittainhard
