{% set version = '2.4-2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-treemap
  version: {{ version|replace("-", "_") }}

source:
  fn: treemap_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/treemap_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/treemap/treemap_{{ version }}.tar.gz


  sha256: 206d32ec0c741a6727e70082e0fef9e5b9e94967178e25d02e65f9ccdb7c6d95
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr
requirements:
  build:
    - r-base 3.4.1
    - r-rcolorbrewer
    - r-colorspace
    - r-data.table >=1.8.8
    - r-ggplot2
    - r-gridbase
    - r-igraph
    - r-shiny >=0.12.0

  run:
    - r-base 3.4.1
    - r-rcolorbrewer
    - r-colorspace
    - r-data.table >=1.8.8
    - r-ggplot2
    - r-gridbase
    - r-igraph
    - r-shiny >=0.12.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('treemap')"  # [not win]
    - "\"%R%\" -e \"library('treemap')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=treemap
  license: GPL-3
  summary: A treemap is a space-filling visualization of hierarchical structures. This package
    offers great flexibility to draw treemaps.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: treemap
# Type: Package
# Title: Treemap Visualization
# Version: 2.4-2
# Date: 2017-01-03
# Authors@R: c( person("Martijn", "Tennekes", email="mtennekes@gmail.com", role=c("aut", "cre")), person("Peter", "Ellis", email="peter.ellis2013nz@gmail.com", role="ctb"))
# Maintainer: Martijn Tennekes <mtennekes@gmail.com>
# Description: A treemap is a space-filling visualization of hierarchical structures. This package offers great flexibility to draw treemaps.
# License: GPL-3
# LazyLoad: yes
# Depends: R (>= 2.10)
# Imports: colorspace, data.table (>= 1.8.8), ggplot2, grid, gridBase, igraph, methods, RColorBrewer, shiny (>= 0.12.0)
# Suggests: knitr
# VignetteBuilder: knitr
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2017-01-03 18:10:35 UTC; vt
# Author: Martijn Tennekes [aut, cre], Peter Ellis [ctb]
# Repository: CRAN
# Date/Publication: 2017-01-04 00:01:24

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
