{% set version = '4.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bnlearn
  version: {{ version|replace("-", "_") }}

source:
  fn: bnlearn_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/bnlearn_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/bnlearn/bnlearn_{{ version }}.tar.gz


  sha256: ca63bee9ceb54a7667b465f3f1ed4cbd3f67787f928d506ecf330ea6d1773fcd
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: parallel, graph, Rgraphviz, lattice, gRain, ROCR
requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('bnlearn')"  # [not win]
    - "\"%R%\" -e \"library('bnlearn')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.bnlearn.com/
  license: GPL (>= 2)
  summary: Bayesian network structure learning, parameter learning and inference. This package
    implements constraint-based (GS, IAMB, Inter-IAMB, Fast-IAMB, MMPC, Hiton-PC), pairwise
    (ARACNE and Chow-Liu), score-based (Hill-Climbing and Tabu Search) and hybrid (MMHC
    and RSMAX2) structure learning algorithms for discrete, Gaussian and conditional
    Gaussian networks, along with many score functions and conditional independence
    tests. The Naive Bayes and the Tree-Augmented Naive Bayes (TAN) classifiers are
    also implemented. Some utility functions (model comparison and manipulation, random
    data generation, arc orientation testing, simple and advanced plots) are included,
    as well as support for parameter estimation (maximum likelihood and Bayesian) and
    inference, conditional probability queries and cross-validation. Development snapshots
    with the latest bugfixes are available from <http://www.bnlearn.com>.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: bnlearn
# Type: Package
# Title: Bayesian Network Structure Learning, Parameter Learning and Inference
# Version: 4.2
# Date: 2017-06-30
# Depends: R (>= 2.14.0), methods
# Suggests: parallel, graph, Rgraphviz, lattice, gRain, ROCR
# Author: Marco Scutari [aut, cre], Robert Ness [ctb]
# Maintainer: Marco Scutari <marco.scutari@gmail.com>
# Description: Bayesian network structure learning, parameter learning and inference. This package implements constraint-based (GS, IAMB, Inter-IAMB, Fast-IAMB, MMPC, Hiton-PC), pairwise (ARACNE and Chow-Liu), score-based (Hill-Climbing and Tabu Search) and hybrid (MMHC and RSMAX2) structure learning algorithms for discrete, Gaussian and conditional Gaussian networks, along with many score functions and conditional independence tests. The Naive Bayes and the Tree-Augmented Naive Bayes (TAN) classifiers are also implemented. Some utility functions (model comparison and manipulation, random data generation, arc orientation testing, simple and advanced plots) are included, as well as support for parameter estimation (maximum likelihood and Bayesian) and inference, conditional probability queries and cross-validation. Development snapshots with the latest bugfixes are available from <http://www.bnlearn.com>.
# URL: http://www.bnlearn.com/
# License: GPL (>= 2)
# LazyData: yes
# NeedsCompilation: yes
# Packaged: 2017-07-01 22:28:22 UTC; fizban
# Repository: CRAN
# Date/Publication: 2017-07-03 13:35:15 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
