{% set version = '2.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-caretensemble
  version: {{ version|replace("-", "_") }}

source:
  fn: caretEnsemble_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/caretEnsemble_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/caretEnsemble/caretEnsemble_{{ version }}.tar.gz


  sha256: 82749d4adfc558d479787b09210a26680388e31109b27416aa2b2f15d0f52f6d
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: caTools, testthat, lintr, randomForest, glmnet, rpart, kernlab, nnet, e1071, ipred, pROC, knitr, mlbench, MASS, gbm, klaR
requirements:
  build:
    - r-base
    - r-caret
    - r-data.table
    - r-digest
    - r-ggplot2
    - r-gridextra
    - r-lattice
    - r-pbapply
    - r-plyr

  run:
    - r-base
    - r-caret
    - r-data.table
    - r-digest
    - r-ggplot2
    - r-gridextra
    - r-lattice
    - r-pbapply
    - r-plyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('caretEnsemble')"  # [not win]
    - "\"%R%\" -e \"library('caretEnsemble')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/zachmayer/caretEnsemble
  license: MIT + file LICENSE
  summary: 'Functions for creating ensembles of caret models: caretList and caretStack.  caretList
    is a convenience function for fitting multiple caret::train models to the same dataset.
    caretStack will make linear or non-linear combinations of these models, using a
    caret::train model as a meta-model, and caretEnsemble will make a robust linear
    combination of models using a glm.'

  license_family: MIT

# The original CRAN metadata for this package was:

# Package: caretEnsemble
# Type: Package
# Title: Ensembles of Caret Models
# Version: 2.0.0
# Date: 2016-02-06
# Authors@R: c(person(c("Zachary", "A."), "Deane-Mayer", role = c("aut", "cre"), email = "zach.mayer@gmail.com"), person(c("Jared", "E."), "Knowles", role=c("aut"), email="jknowles@gmail.com"))
# URL: https://github.com/zachmayer/caretEnsemble
# BugReports: https://github.com/zachmayer/caretEnsemble/issues
# Description: Functions for creating ensembles of caret models: caretList and caretStack.  caretList is a convenience function for fitting multiple caret::train models to the same dataset. caretStack will make linear or non-linear combinations of these models, using a caret::train model as a meta-model, and caretEnsemble will make a robust linear combination of models using a glm.
# Depends: R (>= 3.2.0)
# Suggests: caTools, testthat, lintr, randomForest, glmnet, rpart, kernlab, nnet, e1071, ipred, pROC, knitr, mlbench, MASS, gbm, klaR
# Imports: methods, pbapply, ggplot2, digest, plyr, lattice, gridExtra, data.table, caret
# License: MIT + file LICENSE
# VignetteBuilder: knitr
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-02-06 16:06:12 UTC; zachary
# Author: Zachary A. Deane-Mayer [aut, cre], Jared E. Knowles [aut]
# Maintainer: Zachary A. Deane-Mayer <zach.mayer@gmail.com>
# Repository: CRAN
# Date/Publication: 2016-02-07 10:50:09

# See
# http://docs.continuum.io/conda/build.html for
# more information about oldmeta.yaml
