{% set version = '1.3-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pbapply
  version: {{ version|replace("-", "_") }}

source:
  fn: pbapply_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/pbapply_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/pbapply/pbapply_{{ version }}.tar.gz


  sha256: 7379b21d1176db5769f5cac858dd12c975736e80a600870180cec9625cf51047
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('pbapply')"  # [not win]
    - "\"%R%\" -e \"library('pbapply')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/psolymos/pbapply
  license: GPL-2
  summary: A lightweight package that adds progress bar to vectorized R functions ('*apply').
    The implementation can easily be added to functions where showing the progress is
    useful (e.g. bootstrap). The type and style of the progress bar (with percentages
    or remaining time) can be set through options. Supports several parallel processing
    backends.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: pbapply
# Type: Package
# Title: Adding Progress Bar to '*apply' Functions
# Version: 1.3-3
# Date: 2017-07-03
# Author: Peter Solymos [aut, cre], Zygmunt Zawadzki [aut]
# Maintainer: Peter Solymos <solymos@ualberta.ca>
# Description: A lightweight package that adds progress bar to vectorized R functions ('*apply'). The implementation can easily be added to functions where showing the progress is useful (e.g. bootstrap). The type and style of the progress bar (with percentages or remaining time) can be set through options. Supports several parallel processing backends.
# Depends: R (>= 3.2.0)
# Imports: parallel
# License: GPL-2
# URL: https://github.com/psolymos/pbapply
# BugReports: https://github.com/psolymos/pbapply/issues
# NeedsCompilation: no
# Packaged: 2017-07-04 02:48:38 UTC; root
# Repository: CRAN
# Date/Publication: 2017-07-04 06:48:29 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
