package:
    name: pyfasta
    version: 0.5.2
source:
    fn: pyfasta-0.5.2.tar.gz
    md5: bf61ab997dca329675c3eb2ee7cdfcf2
    url: https://pypi.python.org/packages/source/p/pyfasta/pyfasta-0.5.2.tar.gz
build:
    entry_points:
        - pyfasta = pyfasta:main
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
test:
    commands:
        - pyfasta extract --help | grep Usage > /dev/null
    imports:
        - pyfasta
    requires:
        - nose
about:
    home: http://github.com/brentp/pyfasta/
    license: MIT
    summary: fast, memory-efficient, pythonic (and command-line) access to fasta sequence
        files

extra:
  recipe-maintainers:
    - brittainhard
