{% set version = '0.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggextra
  version: {{ version|replace("-", "_") }}

source:
  fn: ggExtra_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ggExtra_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ggExtra/ggExtra_{{ version }}.tar.gz


  sha256: 7469e77b231d13a56b0d789e9351513f0145bd44a2fd53dc309849360253cf6f
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr (>= 1.7), rmarkdown, rstudioapi (>= 0.5), testthat, vdiffr, fontquiver, svglite, withr, devtools
requirements:
  build:
    - r-base
    - r-colourpicker >=0.1
    - r-ggplot2 >=2.2.0
    - r-gtable >=0.2.0
    - r-miniui >=0.1.1
    - r-shiny >=0.13.0
    - r-shinyjs >=0.5.2

  run:
    - r-base
    - r-colourpicker >=0.1
    - r-ggplot2 >=2.2.0
    - r-gtable >=0.2.0
    - r-miniui >=0.1.1
    - r-shiny >=0.13.0
    - r-shinyjs >=0.5.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ggExtra')"  # [not win]
    - "\"%R%\" -e \"library('ggExtra')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/daattali/ggExtra
  license: MIT + file LICENSE
  summary: Collection of functions and layers to enhance 'ggplot2'. The main function is ggMarginal(),
    which can be used to add marginal histograms/boxplots/density plots to 'ggplot2'
    scatterplots.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: ggExtra
# Title: Add Marginal Histograms to 'ggplot2', and More 'ggplot2' Enhancements
# Version: 0.7
# Authors@R: c( person("Dean", "Attali", , "daattali@gmail.com", role = c("aut", "cre")), person("Christopher", "Baker", , "chriscrewbaker@gmail.com", role = "ctb") )
# Description: Collection of functions and layers to enhance 'ggplot2'. The main function is ggMarginal(), which can be used to add marginal histograms/boxplots/density plots to 'ggplot2' scatterplots.
# URL: https://github.com/daattali/ggExtra
# BugReports: https://github.com/daattali/ggExtra/issues
# Depends: R (>= 3.1.0)
# Imports: colourpicker (>= 0.1), ggplot2 (>= 2.2.0), grid (>= 3.1.3), gtable (>= 0.2.0), miniUI (>= 0.1.1), shiny (>= 0.13.0), shinyjs (>= 0.5.2), utils, grDevices
# Suggests: knitr (>= 1.7), rmarkdown, rstudioapi (>= 0.5), testthat, vdiffr, fontquiver, svglite, withr, devtools
# License: MIT + file LICENSE
# SystemRequirements: pandoc with https support
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2017-06-24 18:01:51 UTC; Dean
# Author: Dean Attali [aut, cre], Christopher Baker [ctb]
# Maintainer: Dean Attali <daattali@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-06-24 22:24:37 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
