{% set version = "3.5.3.0" %}

package:
  name: typing
  version: {{ version }}

source:
  fn: typing-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/typing/typing-{{ version }}.tar.gz
  sha256: ca2daac7e393e8ee86e9140cd0cf0172ff6bb50ebdf0b06281770f98f31bff21

build:
    number: 0
    script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - typing

about:
  home: https://docs.python.org/3.5/library/typing.html
  license: PSF
  license_file: LICENSE
  summary: 'Type Hints for Python - backport for Python<3.5'

extra:
  recipe-maintainers:
    - brittainhard
